export const APP_CONSTANTS = {
  WEBSOCKET: {
    ACK_TIMEOUT_MS: 5000,
    RECONNECT_ATTEMPTS: 5,
    RECONNECT_DELAY_MS: 1000,
    TRANSPORTS: ['websocket'],
  },

  VALIDATION: {
    TASK_TITLE_MIN_LENGTH: 1,
    TASK_TITLE_MAX_LENGTH: 200,
    REQUIRED_FIELD_MESSAGE: 'This field is required',
  },

  UI: {
    TOAST_DEFAULT_DURATION_MS: 3500,
    TOAST_ERROR_DURATION_MS: 5000,
    DEBOUNCE_TIME_MS: 300,
    ANIMATION_DURATION_MS: 250,
  },

  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    LOCKED: 423,
    INTERNAL_SERVER_ERROR: 500,
  },

  LOCK_SUCCESS_STATUSES: [200, 204, 404, 409],

  API_ENDPOINTS: {
    TASKS: '/tasks',
  },
} as const;
